### ISSUE TITLE
Mapbox Studio changes name of source

### ISSUE THREAD

**Issue by jirik** [klokantech/gl-style-package-spec#11]
Mapbox Studio sometimes changes name of the source from "openmaptiles" to "composite". It happened to me when I was changing source of the layer in Mapbox Studio (because it did not exist). When this renaming happens, the produces style.json will not pass the test, because "openmaptiles" source does not exist.

**Comment by klokan** [comment]
We should be able to add metadata preventing compositing in mapbox studio to the header of the JSON file.

**Comment by jirik** [comment]
Do you mean to set `mapbox:autocomposite` to false?
https://github.com/openmaptiles/osm-bright-gl-style/blob/master/style.json#L36
I have just tried it for one style and it seems it works.

**Comment by jirik** [comment]
Property `mapbox:autocomposite` set to false in following styles: dark-matter, klokantech-basic, oldmapsonline, osm-brigth, positron, toner.

Should I also add test to gl-style-package-spec? E.g. it would fail if `mapbox:autocomposite === true`?

**Comment by jirik** [comment]
Closing, test not added.
