### ISSUE TITLE
Tileset compatibility + version compatibility

### ISSUE THREAD

**Issue by klokan** [klokantech/gl-style-package-spec#2]
On OSM2VectorTiles we have made the compatibility by checking metadata name property for a substring match on "OSM2VectorTiles" and "V2". This is not really nice.
We should improve this approach and make it more general - to be usable for other tilesets as well.

Let's use inside of the GL Style JSON in the metadata section:
```
"metadata": {
        "openmaptiles:version": "3.x",
    },
```
The version supports only X-Ranges described https://github.com/npm/node-semver#x-ranges-12x-1x-12- so for example: `3` = `3.x` = `3.X` = `3.*` or `3.0` = `3.0.x` ...

**Comment by klokan** [comment]
The tileset must have identifier "openmaptiles" in the JSON style to be used/replaced by the viewer, like
```
"sources" {
        "openmaptiles": "protocol://whatever"
    },
```

**Comment by jirik** [comment]
Done for openmaptiles gl-styles and klokantech/oldmapsonline-gl-style. Both in repo and Mapbox Studio.
