### ISSUE TITLE
mapbox-gl-style-spec deprecated

### ISSUE THREAD

**Issue by nlehuby** [klokantech/gl-style-package-spec#21]
The mapbox-gl-style-spec used in the tests seems deprecated : 
https://github.com/mapbox/mapbox-gl-style-spec

Is it still relevant to use it ?

**Comment by daliborjanak** [comment]
No, the repo has been merged with javascript. Repo is deprecated, specification no. Everybody is using it on production

**Comment by jirik** [comment]
@daliborjanak Actually we need the latest version because of Maputnik 1.1.0, so I upgraded it.
