### ISSUE TITLE
Add warning for formatting

### ISSUE THREAD

**Issue by klokan** [klokantech/gl-style-package-spec#6]
The script should print warning (or later on even an error?) in case the formatting of the style.json is not exactly the same as produced by `gl-style-format` - and recommend to run this utility before commit.

Internal note for implementation:
```
npm install -g mapbox-gl-style-spec
gl-style-format style1.json > style.json
```

**Comment by jirik** [comment]
Done in 98a3068332cab9696d9c01a24f49918993d9fea6
